language: node_js
os:
  - linux
#services:
#  - docker
node_js:
  - "6.10.1"
sudo: true
before_script:
  #- docker build -t waecm-bsp1 .
  #- docker run -v $(pwd):/usr/src/app -p 8080:3000 waecm-bsp1 selenium &

  # evtl -t -> macht eine shell auf, sodass nicht geschlossen wird
  # -d -> detach
script:
  #- sleep 3m
  #- ps -ef | grep docker
  #- docker ps
  #- curl https://localhost:8080 --insecure
  - node tests/selenium/selenium-webdriver-simple.js
  #- ps -ef | grep docker
  # - docker run --name waecm-bsp1-test -comv $(pwd):/usr/src/app -p 8080:3000 waecm-bsp1 test
  # - node tests/selenium/selenium-webdriver-simple.js
after_script:
  #- docker rm -f waecm-bsp1-test

deploy:
 provider: script
 skip_cleanup: true
 script: chmod 600 geppi_linux.private && ssh -o StrictHostKeyChecking=no -i ./geppi_linux.private
   ec2-user@ec2-54-149-153-204.us-west-2.compute.amazonaws.com 'sudo ./deploy.sh'
 on:
   branch: master

  #plz no steal key
addons:
  sauce_connect:
    username: "jobrot94"
    access_key: "ab4eda0a-c39c-4107-b8d3-1a3ab459d16f"
