language: node_js

os:
  - linux
services:
  - docker

node_js:
  - "6.10.1"

sudo: true

before_script:
  - docker build -t waecm-bsp1 .

script:
  - docker run -v $(pwd):/usr/src/app -p 8080:3000 waecm-bsp1 test
