language: node_js
os:
  - linux
services:
  - docker
node_js:
  - "6.10.1"
sudo: true
before_script:
  - openssl aes-256-cbc -K $encrypted_df2dee2886a8_key -iv $encrypted_df2dee2886a8_iv
    -in geppi_linux.private.enc -out ./deploy_key -d
  - docker build -t waecm-bsp1 .
script:
  - docker run --name waecm-bsp1-test -comv $(pwd):/usr/src/app -p 8080:3000 waecm-bsp1 test
after_script:
  - docker rm -f waecm-bsp1-test
deploy:
 provider: script
 skip_cleanup: true
 script: chmod 600 deploy_key && ssh -o StrictHostKeyChecking=no -i ./deploy_key
   ec2-user@ec2-54-149-153-204.us-west-2.compute.amazonaws.com 'sudo ./deploy.sh'
 on:
   branch: master
