language: node_js
os:
  - linux
services:
  - docker
node_js:
  - "6.10.1"
sudo: true
before_script:
  - docker build -t waecm .
  - openssl aes-256-cbc -K $encrypted_df2dee2886a8_key -iv $encrypted_df2dee2886a8_iv
    -in geppi_linux.private.enc -out ./deploy_key -d

script:
  #- ps -ef | grep docker
  - docker run -v $(pwd):/usr/src/app -p 8080:3000 --name test-container waecm test
  - chmod 600 deploy_key && ssh -o StrictHostKeyChecking=no -i ./deploy_key ec2-user@ec2-54-201-136-143.us-west-2.compute.amazonaws.com 'sudo ./deploy_test.sh'
  - sleep 2m
  - node tests/selenium/selenium-webdriver-simple.js
  # - node tests/selenium/selenium-webdriver-simple.js
after_script:
  - docker rm -f test-container
  - chmod 600 deploy_key && ssh -o StrictHostKeyChecking=no -i ./deploy_key ec2-user@ec2-54-201-136-143.us-west-2.compute.amazonaws.com 'sudo ./stop_test.sh'
deploy:
 provider: script
 skip_cleanup: true
 script: chmod 600 deploy_key && ssh -o StrictHostKeyChecking=no -i ./deploy_key
   ec2-user@ec2-54-201-136-143.us-west-2.compute.amazonaws.com 'sudo ./deploy.sh'
 on:
   branch: master

#plz no steal key
addons:
  sauce_connect:
    username: "jobrot94"
    access_key: "ab4eda0a-c39c-4107-b8d3-1a3ab459d16f"
